### PR TITLE
fix: path segments and query params combined

### LINKED ISSUE #1058: Path segments appended after query parameters corrupt the iframe URL
When an external site is configured with query parameters in its URL (e.g. `https://example.com/app?jwt={jwt}`), visiting a subpath like `/apps/external/1/some/path` produces a malformed URL.

The path is naively concatenated onto the full URL string, resulting in: `https://example.com/app?jwt=TOKEN/some/path`

Instead of the correct version: `https://example.com/app/some/path?jwt=TOKEN`

This causes query parameters – including the {jwt} token – to be corrupted, as the path segments become part of the query parameter value. The external site never receives a valid JWT, breaking authentication for any subpath navigation.

### PR DESCRIPTION
**Pull request by pReya**
closes #1058 

- When visiting a subpath of an external site whose URL contains query parameters (e.g. ?jwt={jwt}), the path was naively concatenated onto the full URL string, producing malformed URLs like https://example.com/app?jwt=TOKEN/some/path
- The URL is now properly parsed with parse_url() so the path is inserted before the query string, producing https://example.com/app/some/path?jwt=TOKEN

### CODE REVIEW

File: lib/Controller/SiteController.php [hunk 1]
```diff
@@ -89,12 +89,27 @@ protected function createResponse(int $id, array $site, string $path = ''): Temp
...
-			$path = $site['url'][-1] == '/' ? $path : '/' . $path;
+			// Parse the URL to properly insert the path before any query parameters
+			$parts = parse_url($site['url']);
+			$basePath = rtrim($parts['path'] ?? '', '/') . '/' . $path;
+
+			$url = $parts['scheme'] . '://' . $parts['host'];
+			if (isset($parts['port'])) {
+				$url .= ':' . $parts['port'];
+			}
+			$url .= $basePath;
```
Comment (provokateurin) [inline lib/Controller/SiteController.php]:
```suggestion

			$url = $parts['scheme'] . '://' . $parts['host'];
			if (isset($parts['port'])) {
				$url .= ':' . $parts['port'];
			}
			$url .= rtrim($parts['path'] ?? '', '/') . '/' . $path;
```
Less confusing to read if it's all done in the correct order.

**Review by provokateurin — CHANGES_REQUESTED** [review]
I'm not so happy about manually assembling the URL again, but I couldn't find a better solution either.

The URL could contain `user` and `pass`, so you need to take care of that as well: https://www.php.net/manual/en/function.parse-url.php#refsect1-function.parse-url-returnvalues

**Comment by pReya** [comment]
> I'm not so happy about manually assembling the URL again, but I couldn't find a better solution either.
> 
> The URL could contain `user` and `pass`, so you need to take care of that as well: https://www.php.net/manual/en/function.parse-url.php#refsect1-function.parse-url-returnvalues

Thanks for the review. I agree about this feeling not very elegant, but I'm afraid this is the only way to handle this. I've added `user` and `pass` parts now, too.

**Review by provokateurin — APPROVED** [review]
Thanks!

**Comment by provokateurin** [comment]
You need to fix psalm. I think in this case it makes sense to throw a RuntimeException if scheme or host are not present, because it should never actually happen in reality.

**Review by provokateurin — APPROVED** [review]
Thanks!
